### ISSUE TITLE
Sample generator handles 'title' tag from sample config

### ISSUE THREAD

**Issue by software-dov** [googleapis/gapic-generator-python#178]
The title tag contains a helpful docstring.

```yaml
---
type: com.google.api.codegen.SampleConfigProto
schema_version: 1.2.0
samples:
- service: google.cloud.language.v1.LanguageService
  rpc: AnalyzeSentiment
  title: Analyze sentiment of text
  region_tag: language_sentiment_text
  description: Analyze sentiment of text
```
