### ISSUE TITLE
Sample generator should break long comments into multiple lines and properly render multi-line comments

### ISSUE THREAD

**Issue by software-dov** [googleapis/gapic-generator-python#200]
A comment block that is more than ~70 characters, including indentation, should be broken up into multiple lines.

Going hand in hand, the sample generator should properly render multi-line comments, e.g.

```
request:
- field: mollusc.class
  value: cephalopoda
  comment: This is a very long comment indicating that the class of the input mollusc is in fact Cephalopoda, including squids, octopuses, cuttlefish, chambered nautiluses, and a few oddball outliers.
- field: mollusc.mass
  value: 10 kg
  comment: The mass of the cephalopod\nincludes any calcerous features, including a shell or cuttlebone.
```
