### ISSUE TITLE
quotes not handled correctly in input and output

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/gapic-generator-python#216]
Default string values are not quoted in the request, and quotes within a string are not handled within a response (and possibly within a request, I haven't checked).

And a spacing issue.

With this config file against the showcase echo service:
```
---
type: com.google.api.codegen.SampleConfigProto
schema_version: 1.2.0
samples:
- service: google.showcase.v1beta1.Echo
  rpc: Echo
  description: A sample of a simple echo request and response
  request:
  - field: content
    comment: The content to be echoed back
    value: a resounding echo...echo...echo
    input_parameter: message
  response:
    - comment:
      - "We simply print the response"
    - print:
      - 'Heard back: "%s"'
      - $resp.content
```

The output (in part) is the following (minus the ##[X], which are my notes referenced below):
```
def sample_echo(message):
    """A sample of a simple echo request and response"""

    client = Echo(
        credentials=credentials.AnonymousCredentials(),
        transport="grpc",
    )

    response = client.echo(
                                                                      ##[1]
      content=a resounding echo...echo...echo)                        ##[2]

    # We simply print the response

    print("Heard back: "{}"".format(response.content))                ##[3]


# [END f39f489e]


def main():
    import argparse

    parser = argparse.ArgumentParser()

    parser.add_argument("--message",
                        type=str,
                        default=a resounding echo...echo...echo)      ##[4]
```

Note:
##[1] Extra blank line. We need to remove it.
##[2] & ##[4] Default value not quoted. Let's quote it. This is release blocker.
##[3] Double quotes `"` within a string not escaped. Let's escape it, just one level (ie no need to try to be sophisticated and do full string parsing to see whether the double quotes in the input are themselves escaped.)
